"""add invitation_bonus

Revision ID: 06f771acca34
Revises: ba43fc21a432
Create Date: 2025-01-05 18:36:48.099898

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '06f771acca34'
down_revision = 'ba43fc21a432'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invitation_bonus', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'invitation_bonus')
    # ### end Alembic commands ###
