"""add sync_at

Revision ID: 23a3c6cf6545
Revises: 06f771acca34
Create Date: 2025-01-25 00:45:21.990958

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '23a3c6cf6545'
down_revision = '06f771acca34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sync_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sync_at')
    # ### end Alembic commands ###
