"""add index

Revision ID: f46914f2abb6
Revises: 23a3c6cf6545
Create Date: 2025-01-25 01:31:12.506051

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f46914f2abb6'
down_revision = '23a3c6cf6545'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_telegram_id', table_name='users')
    # ### end Alembic commands ###
